# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e9e5768fb899477f55a7f68b6afad50881a49d1f0bac5b739b59f0438c5c78a8e69e0df3fc69af82c36065c96edf66801b694df1e540fe210356ecb7638514b

test:
  secret_key_base: beaeb52a28ec649c3fe266fb409fdc09e5f875856f154f7dde23ef7bc8bcf3b32f2d9b0896cf00fdcf872a985d52eb31b07222e2b3e4c1eb0241c9724765fc44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
